<p>
  <a
    property="dct:title"
    rel="cc:attributionURL"
    href="https://github.com/SkyWolfXP/discord-channel-html-transcript"
  >Discord Channel HTML Transcript</a> by <a
    rel="cc:attributionURL dct:creator"
    property="cc:attributionName"
    href="https://github.com/SkyWolfXP"
  >SkyWolfXP</a> is licensed under <a
    href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1"
    target="_blank"
    rel="license noopener noreferrer"
    style="display:inline-block;"
  >CC BY-SA 4.0
  </a>
</p>