<div class="footer user-select-none">
  <a
    property="dct:title"
    rel="cc:attributionURL"
    href="https://github.com/SkyWolfXP/discord-channel-html-transcript"
    class="markup__link"
  >
    Discord Channel HTML Transcript
  </a>
  &nbsp;by&nbsp;
  <a
    rel="cc:attributionURL dct:creator"
    property="cc:attributionName"
    href="https://github.com/SkyWolfXP"
    class="markup__link"
  >
    SkyWolfXP
  </a>
  &nbsp;is licensed under&nbsp;
  <a
    href="https://creativecommons.org/licenses/by-sa/4.0/"
    target="_blank"
    rel="license noopener noreferrer"
    style="display:inline-block;"
    class="markup__link"
  >
    CC BY-SA 4.0
  </a>
  &nbsp;•&nbsp;
  <a
    href="https://github.com/SkyWolfXP/discord-channel-html-transcript/#legal"
    class="markup__link"
  >
    Legal Compliance
  </a>
</div>